MarketPlace/Controllers/CartController.cs
using MarketPlace.Core.Contracts.ICartService;
using MarketPlace.Core.Contracts.IProductService;
using MarketPlace.Core.Models.AddressDto;
using MarketPlace.Core.Models.CartDto;
using MarketPlace.Core.Models.OrderInfoDto;
using MarketPlace.Infrastructure.Data;
using MarketPlace.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MarketPlace.Controllers
{
    [Authorize]
    public class CartController : BaseController
    {
        private readonly ApplicationDbContext data;
        private readonly ICartService serviceCart;
        public CartController(ApplicationDbContext data, ICartService serviceCart)
              : base(data)
        {
            this.data = data;
            this.serviceCart = serviceCart;
        }

        public async Task<IActionResult> Cart()
        {
            string userId = GetUserId();

            if (userId == null)
            {
                return Unauthorized();
            }

            var productBuyer = await serviceCart.AllCartAsync(userId);

            return View(productBuyer);
        }

        public async Task<IActionResult> AddTocart(int id)
        {
            var productToAdd = await data.Products.FindAsync(id);

            if (productToAdd == null)
            {
                return BadRequest();
            }

            string userId = GetUserId();

            if (productToAdd.SellerId == userId)
            {
                return BadHttpRequestException("You can't buy your own product!");
            }

            var checkProduct = await data.ProductBuyers
                  .Where(p => p.ProductId == productToAdd.Id && p.BuyerId == userId)
                  .FirstOrDefaultAsync();

            if (checkProduct != null)
            {
                return BadHttpRequestException("You already have this product in your cart!");
            }

            var address = await data.ShipingAddresses
                .Where(p => p.UserId == userId)
                .FirstOrDefaultAsync();
            if (address == null)
            {
                return RedirectToAction(nameof(AddAddress));
            }

            var productBuyer = new ProductBuyer
            {
                ProductId = productToAdd.Id,
                BuyerId = userId,
                ShipingAddressId = address.Id,
            };
            productToAdd.CartQuantity = 1;
            productToAdd.Quantity--;


            await data.ProductBuyers.AddAsync(productBuyer);
            await data.SaveChangesAsync();

            return RedirectToAction(nameof(Cart));
        }

        private static IActionResult BadHttpRequestException(string v)
        {
            var badRequest = new BadRequestObjectResult(v);

            return badRequest;
        }

        public async Task<IActionResult> Buy(string buyerId)
        {
            buyerId = GetUserId();

            var products = await data.ProductBuyers
                .Where(p => p.BuyerId == buyerId)
                .ToListAsync();


            //var sellerId = await data.Products.Select(p => p.SellerId).FirstOrDefaultAsync();

            //if (sellerId == null)
            //{
            //    return BadRequest();
            //}

            var address = await data.ShipingAddresses
                .Where(p => p.UserId == buyerId)
                .FirstOrDefaultAsync();

            if (address == null)
            {
                return RedirectToAction(nameof(AddAddress));
            }

            if (products == null)
            {
                return BadRequest();
            }

            var productNames = await data.ProductBuyers
                .Where(p => p.BuyerId == buyerId)
                .Select(p => p.Product.Name)
                .ToListAsync();
            var productIds = await data.ProductBuyers
                .Where(p => p.BuyerId == buyerId)
                .Select(p => p.ProductId)
                .ToListAsync();
            var sellerId = await data.ProductBuyers
                .Where(p => p.BuyerId == buyerId)
                .Select(p => p.Product.SellerId)
                .ToListAsync();


            if (productNames == null)
            {
                return BadRequest();
            }

            var order = new Order
            {
                BuyerId = buyerId,
                SellerId = sellerId[0],
                OrderDate = DateTime.Now,
                ShipingAddress = address.Street + ", " + address.City + ", " + address.Country + ", " + address.ZipCode,
                ProductName = string.Join(", ", productNames),
                ProductId = string.Join(", ", productIds)

            };

            foreach (var product in products)
            {
                data.ProductBuyers.Remove(product);
            }

            await data.Orders.AddAsync(order);
            await data.SaveChangesAsync();

            return RedirectToAction(nameof(Cart));
        }

        [HttpGet]
        public async Task<IActionResult> RemoveFromCart(CartFormModel model)
        {
            var userId = GetUserId();

            if (userId == null)
            {
                return Unauthorized();
            }
            var productToRemove = await data.ProductBuyers
                .Where(p => p.ProductId == model.Id && p.BuyerId == userId)
                .FirstOrDefaultAsync();


            return View(productToRemove);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(int id)
        {
            var productToRemove = await data.ProductBuyers
                .Where(p => p.ProductId == id && p.BuyerId == GetUserId())
                .FirstOrDefaultAsync();

            var product = await data.Products.FindAsync(id);

            if (product == null)
            {
                return BadRequest();
            }

            if (productToRemove == null)
            {
                return BadRequest();
            }
            product.Quantity++;


            data.ProductBuyers.Remove(productToRemove);
            data.SaveChanges();

            return RedirectToAction(nameof(Cart));
        }

        [HttpGet]
        public async Task<IActionResult> AddAddress()
        {
            AddressFormModel model = new()
            {
                Products = await data.ProductBuyers.Where(p => p.BuyerId == GetUserId()).Select(p => p.Product).ToListAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddAddress(AddressFormModel model)
        {
            string userId = GetUserId();

            if (userId == null)
            {
                return Unauthorized();
            }

            var address = new ShipingAddress
            {
                Id = model.Id,
                Recipient = model.Recipient,
                City = model.City,
                Country = model.Country,
                ZipCode = model.ZipCode,
                Street = model.Street,
                UserId = userId,

            };

            if (address == null)
            {
                return BadRequest();
            }

            data.ShipingAddresses.Add(address);
            data.SaveChanges();

            return RedirectToAction(nameof(Cart));
        }
    }
}

MarketPlace/Controllers/OrderController.cs
using MarketPlace.Core.Contracts.IOrderService;
using MarketPlace.Core.Models.OrderInfoDto;
using MarketPlace.Core.Models.Rating;
using MarketPlace.Infrastructure.Data;
using MarketPlace.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using System.Security.Claims;

namespace MarketPlace.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext data;
        private readonly IOrderService orderService;

        public OrderController(ApplicationDbContext _data,IOrderService _orderService)
        {
            data = _data;
            orderService = _orderService;
        }

        [HttpGet]
        public async Task<IActionResult> OrderInfo()
        {
            var userId = GetUserId();

            if (userId == null)
            {
                return Unauthorized();
            }

           var order= await orderService.AllOrdersAsync(userId);

            if (order == null)
            {
                return BadRequest();
            }

            return View(order);
        }

        public async Task<IActionResult> Details(int id)
        {
            var order = await data.Orders.FindAsync(id);

            if (order == null)
            {
                return BadRequest();
            }

            var allProducts = await data.Products.ToListAsync();

            string[] productId = order.ProductId.Split(',');

            if (productId.Length == 0)
            {
                return BadRequest();
            }

            List<OrderDetailsModel> products = new List<OrderDetailsModel>();

            if (productId.Length > 0)
            {
                int index = productId.Length;
                int i = 0;
                while (index > 0)
                {
                    var product = allProducts
                   .Where(p => p.Id == int.Parse(productId[i]))
                   .Select(p => new OrderDetailsModel()
                   {
                       DateOfOrder = order.OrderDate.ToString("dd/MM/yyyy/HH:mm"),
                       ImageUrl = p.Image,
                       ProdctName = p.Name,
                       ShipingAddress = order.ShipingAddress,
                       ProductId = p.Id

                   }).ToList();

                    if (product == null)
                    {
                        return BadRequest();
                    }

                    index--;
                    i++;
                    products.AddRange(product);
                }
                return View(products);
            }
            return RedirectToAction(nameof(OrderInfo));
        }

        public async Task<IActionResult> Rating(int id)
        {
            var userId = GetUserId();

            if (userId == null)
            {
                return Unauthorized();
            }

           var model = await orderService.RatingAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Rating(int id, RatingModel model)
        {
            var userId = GetUserId();

            if (userId == null)
            {
                return Unauthorized();
            }

            var product = await data.Products.FindAsync(id);

            if (product == null)
            {
                return BadRequest();
            }

           var result = await orderService.RatingResultAsync(id, model);

            return RedirectToAction(nameof(OrderInfo));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var order = await data.Orders.FindAsync(id);

            if (order == null)
            {
                return BadRequest();
            }

            data.Orders.Remove(order);
            await data.SaveChangesAsync();

            return RedirectToAction(nameof(OrderInfo));
        }

        private string GetUserId()
        {
            return User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? string.Empty;
        }
    }
}

MarketPlace/Controllers/ProductController.cs
using MarketPlace.Core.Contracts;
using MarketPlace.Core.Contracts.IProductService;
using MarketPlace.Core.Models;
using MarketPlace.Core.Models.ProductDto;
using MarketPlace.Infrastructure.Data;
using MarketPlace.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;

namespace MarketPlace.Controllers
{
    [Authorize]
    public class ProductController : BaseController
    {
        private readonly ApplicationDbContext data;
        private readonly IProductService productService;
        public ProductController(ApplicationDbContext data, IProductService productService)
              : base(data)
        {
            this.data = data;
            this.productService = productService;
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {

            ProductFormModel model = new ProductFormModel()
            {
                Categories = await productService.AllCategoryAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ProductFormModel model)
        {
            var userId = GetUserId();

            if (userId == null)
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                model.Categories = await productService.AllCategoryAsync();

                return View(model);
            }

            await productService.CreateAsync(model, userId);

            return RedirectToAction(nameof(All));
        }
        [AllowAnonymous] 
        public async Task<IActionResult> All([FromQuery] AllProductQueryModel query)
        {
            var model = await productService.AllAsync(
                query.Category,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                query.ProductsPerPage);

            query.TotalProductsCount = model.TotalProductsCount;
            query.Products = model.Products;
            query.Categories = await data.Categories.Select(c => c.Name).ToListAsync();

            return View(query);

        }
        public async Task<IActionResult> Mine()
        {
            string userId = GetUserId();

            IEnumerable<AllProductsModel> products = await productService.AllProductsUserIdAsync(userId);

            if (userId == null)
            {
                return Unauthorized();
            }

            // await productService.AllProductsUserIdAsync(userId);

            return View(products);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = GetUserId();

            if (userId == null)
            {
                return Unauthorized();
            }

            await productService.DeleteAsync(id);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var userId = GetUserId();

            if (userId == null)
            {
                return Unauthorized();
            }

            if (!await productService.ExistAsync(id))
            {
                return BadRequest();
            }

            var product = await productService.GetProductByIdAsync(id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, ProductFormModel model)
        {
            var userId = GetUserId();

            if (userId == null)
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                model.Categories = await productService.AllCategoryAsync();

                return View(model);
            }

            var product = await productService.GetProductByIdAsync(id);

            if (product == null)
            {
                return NotFound();
            }

            await productService.EditAsync(id, model);

            return RedirectToAction(nameof(Mine));
        }
    }
}

MarketPlace/Views/Shared/_Layout.cshtml
@using static MarketPlace.Extensions.ClaimPrincipalExtensions

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -Best MarketPlace</title>
     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> 
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MarketPlace.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/UserArea/Mine/Mine.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
   @*  <link rel="icon" type="image/x-icon" href="assets/favicon.ico" /> *@

</head>
<body style="background-color:powderblue; margin:0 auto;">
    <header style="background-color:#f8f9fa;">
        <nav class="navbar navbar-expand-sm bg-info navbar-dark shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Marketplace</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (this.User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Mine" style="color:black">My Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Add" style="color:black">Add Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="AddAddress" style="color:black">Shipping Address</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Order" asp-action="OrderInfo" style="color:black">Order Info</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="All" style="color:black">All Products</a>
                        </li>
                        @if (User?.IsInRole("Administrator") ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Dashboard" style="color:red">Admin Area</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted py-3">
        <div class="container text-center">
            <a>&copy; @DateTime.Now.Year - Marketplace</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/scripts.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<style>

    .navbar {
        padding: 10px 20px;
        margin-bottom: 20px;
    }

    .navbar-brand {
      
        font-weight: bold;
    }



    .my-products-link:hover {
        color: #007bff;
        text-shadow: 0px 0px 3px rgba(0, 123, 255, 0.5);
    }

    .navbar-nav .nav-link {
        font-size: 1.1rem;
        padding: 10px 15px;
        transition: color 0.3s ease, text-shadow 0.3s ease;
    }


    .navbar-nav:hover .nav-link:hover {
        transform: scale(1.1);
        color: white !important;
    }


</style>

MarketPlace/Views/Shared/_ProductPartial.cshtml
@using MarketPlace.Core.Models

@model AllProductsModel


<div class="col-md-4">
    <div class="card mb-3 product-card">

        <article class="card-body text-center">
            <h5 class="card-title mt-3">@Model.Name</h5>

            <img class="card-img-top mx-auto d-block product-image" src="@Model.Image" alt="Image of @Model.Name">

            <ul class="list-unstyled mt-3 product-details">
                <li class="mb-1">
                    <span class="fw-bold">Added on: </span>@Model.CreatedOn
                </li>
                <li class="mb-1">
                    <span class="fw-bold">Category: </span>@Model.Category
                </li>
                <li class="mb-1">
                    <span class="fw-bold">Price: </span>@Model.Price Euro
                </li>
                <li class="mb-1">
                    <span class="fw-bold">Seller: </span>@Model.Seller
                </li>
                <li class="mb-1">
                    <span class="fw-bold">Quantity: </span>@Model.Quantity
                </li>
                <li class="mb-1">
                    <span class="fw-bold">Rating: </span>@Model.Rating
                </li>
            </ul>
        </article>

        <div class="card-footer text-center">
            @if (User.Identity.Name == Model.Seller)
            {
                <a asp-controller="Product" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-dark mb-2 w-100 fw-bold">Edit</a>
                <a asp-controller="Product" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-danger mb-3 w-100 fw-bold">Delete</a>
            }
            else
            {
                <a asp-controller="Cart" asp-action="AddToCart" asp-route-id="@Model.Id" class="btn btn-outline-success mb-2 w-100 fw-bold">Add to Cart</a>
                <a asp-controller="Product" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-outline-primary mb-3 w-100 fw-bold">Details</a>
            }
        </div>
    </div>
</div>

<style>
    /* Card Styles */
    .product-card {
        width: 15rem;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);
        border-radius: 10px;
        transition: transform 0.3s, box-shadow 0.3s;
    }

        .product-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
        }

    /* Image Styling */
    .product-image {
        width: 128px;
        height: 128px;
        border-radius: 50%;
        border: 2px solid #343a40;
        object-fit: cover;
    }

    /* Product Details */
    .product-details li {
        font-size: 0.95rem;
        color: #6c757d;
    }

        .product-details li span.fw-bold {
            color: #343a40;
        }

    /* Button Styling */
    .btn {
        font-size: 0.95rem;
        border-radius: 5px;
    }

    .btn-outline-success {
        border-color: #28a745;
        color: #28a745;
    }

    .btn-outline-danger {
        border-color: #dc3545;
        color: #dc3545;
    }

    .btn-outline-primary {
        border-color: #007bff;
        color: #007bff;
    }

    .btn-outline-dark {
        border-color: #343a40;
        color: #343a40;
    }

    /* Card Footer */
    .card-footer {
        background-color: #f8f9fa;
        border-top: 1px solid #e9ecef;
        padding-top: 10px;
    }
</style>